### ISSUE TITLE
Gui Wiring tool breaks game

### ISSUE THREAD

**Issue by Endleon201** [wiremod/wire-extras#103]
When I use said tool on unwired parts, it works perfectly. The second I try to use it on already wired together parts, it whites out my screen and sends the following error:

[wire-extras] addons/wire-extras/lua/weapons/gmod_tool/stools/gui_wiring.lua:157: attempt to concatenate local 'port' (a nil value)
  1. GUIWiring_GetEntPortKey - addons/wire-extras/lua/weapons/gmod_tool/stools/gui_wiring.lua:157
   2. GUIWiring_ShowGUI - addons/wire-extras/lua/weapons/gmod_tool/stools/gui_wiring.lua:266
    3. func - addons/wire-extras/lua/weapons/gmod_tool/stools/gui_wiring.lua:127
     4. unknown - lua/includes/extensions/net.lua:32

I don't know enough Lua to understand exactly what happened, so please explain to me if I'm doing anything stupid.

**Comment by thegrb93** [comment]
It's definitely the tool's fault

**Comment by Endleon201** [comment]
> It's definitely the tool's fault

Than how can I fix it?

**Comment by thegrb93** [comment]
Need to debug and fix the lua code

**Comment by Endleon201** [comment]
> Need to debug and fix the lua code

Who will get on this?

**Comment by thegrb93** [comment]
The problem is here: https://github.com/wiremod/wire-extras/blob/master/lua/weapons/gmod_tool/stools/gui_wiring.lua#L266
port0 has 'nil' Name

**Comment by Endleon201** [comment]
> The problem is here: https://github.com/wiremod/wire-extras/blob/master/lua/weapons/gmod_tool/stools/gui_wiring.lua#L266
> port0 has 'nil' Name

Do I remove said line??

**Comment by thegrb93** [comment]
No, need to figure out what the contents of the tables are and see why Name is nil.

**Comment by thegrb93** [comment]
Looks like d20c969c2fd6d80f4ed2db636f69aa6b99fcb641 caused the issue
