### ISSUE TITLE
holoSetPose constantly flashing pose parameter

### ISSUE THREAD

**Issue by diemarthaha** [wiremod/wire-extras#110]
Whenever I use the function it either doesn't work, or just repeatedly flashes the animation for it. I've only used a TF2 model for this

https://user-images.githubusercontent.com/59637734/164960869-b7139e87-0e42-467c-80d4-0aa6db4559c1.mp4

.

**Comment by thegrb93** [comment]
Can you provide some e2 code to test with?

**Comment by diemarthaha** [comment]
[test.txt](https://github.com/wiremod/wire-extras/files/8596236/test.txt)

**Comment by thegrb93** [comment]
I found pose parameters have to get set every frame which kinda explains the flickering. As for why the pose parameter is messing with the animation. idk

**Comment by Blu-x92** [comment]
holoanim / holosetpose in general is broken ever since #64
i just reverted the changes ony my private build seems to work flawless again.

**Comment by thegrb93** [comment]
Sure we can revert it but #55 needs to be fixed at the same time.

**Comment by thegrb93** [comment]
Also since when does ReadUInt return nil? wiki says nothing of that

**Comment by thegrb93** [comment]
I went ahead and fixed that lua error

**Comment by Blu-x92** [comment]
i never had the issues of #55 at that time and i still have multiple e2s that have up to 5 holosetpose run at the same time that are now broken. I think it just has to be called on tick? Anyone who is going to use them will be calling them on tick anyway?

**Comment by thegrb93** [comment]
Try the example code in it and if it isn't bugged anymore maybe gmod dev fixed and and this can be reverted.

**Comment by SpaxscE** [comment]
holo pose parameters are still completely broken. Please revert this change. The flickering has never been an real issue.

**Comment by thegrb93** [comment]
Hi, nice 2 years later. I'm not reverting because then people will complain about the revert causing the other issue to pop up. Whatever is broken needs to be debugged and fixed.

**Comment by SpaxscE** [comment]
this version doesnt even have holoanim anymore as it seems

**Comment by SpaxscE** [comment]
The more i dig, the deeper the rabbithole goes. So wiremod does in fact have anim/setpose, however it is not being uploaded to the workshop. https://github.com/wiremod/wire/pull/3113

Workshop reuploads of wire-extras still use the broken version of #64 and they sure will conflict with holoanim from wiremod itself once it is uploaded to workshop. What a complete disaster. This function will remain broken forever.
