### ISSUE TITLE
Directional Radios don't duplicate correctly

### ISSUE THREAD

**Issue by Skating-Fool** [wiremod/wire-extras#115]
When a directional radio is duplicated using adv dupe 1 or 2 the radio will lose its inputs/outputs and the new entity won't count towards the max_wdrk limit.

When a directional radio is duplicated using the normal gmod duplicator it keeps its inputs/outpus but the new entity still doesn't count towards the max_wdrk limit.

I also get the following error when spawning a duplicated directional radio that has something wired to it. This does not show up when duped with nothing wired to it.
```
[wire-extras] addons/wire-extras/lua/entities/base_wdr_entity/init.lua:213: attempt to index field 'Inputs' (a nil value)
  1. unknown - addons/wire-extras/lua/entities/base_wdr_entity/init.lua:213
```
![20230724153602_1](https://github.com/wiremod/wire-extras/assets/106551752/d4a34250-45a5-46b3-866f-c82b5f486145)
https://www.youtube.com/watch?v=-5CslAutvTc

**Comment by thegrb93** [comment]
See if that update fixed it
