### ISSUE TITLE
Directional Radios don't save tx mode when duped

### ISSUE THREAD

**Issue by Skating-Fool** [wiremod/wire-extras#116]
When a directional radio is duped is_tx isn't saved, as a result, the new duped radio defaults to being a receiver.
![20230725003119_1](https://github.com/wiremod/wire-extras/assets/106551752/464678a5-f547-4699-ad87-dad2bc402cc3)

**Comment by thegrb93** [comment]
Mind trying that fix?

**Comment by Skating-Fool** [comment]
> Mind trying that fix?
It saves now. Thanks dude!
