### ISSUE TITLE
After "E2 Compiler Rewrite" commit to wiremod, a Lua error started appearing.

### ISSUE THREAD

**Issue by unnamed9** [wiremod/wire-extras#120]
Actually, subject.
After this commit:
https://github.com/wiremod/wire/commit/44d9366a5fc1dd9c4359035b53fa1902a0c4a0ca
This Lua error started appearing:
```
Warning: Operator operator= is now redundant. Ignoring registration. (at line 1317) @entities/gmod_wire_expression2/core/custom/tracesystem.lua
```

**Comment by Vurv78** [comment]
Fixed by https://github.com/wiremod/wire-extras/commit/dd4cb42dac7b4a1e49bcd2261a7ef3207347bcab
