### ISSUE TITLE
HoloAnim prevents e2 from being spawned

### ISSUE THREAD

**Issue by TheFreezebug** [wiremod/wire-extras#33]
I can't find a lua error :s, they're not showing up for some strange reason, otherwise i'd have just put in a pull request and fixed it myself. 

Any E2 that has holoAnim code in it will not spawn.

**Comment by TomyLobo** [comment]
Can you provide an example E2?

**Comment by TheFreezebug** [comment]
Nevermind, i'm stupid.  Was using a weird model, and some of the holoanim shit didn't get moved over on an FTP transfer.
