### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by theaoneone** [wiremod/wire-extras#39]
[ERROR] addons/wire-extras-master/lua/autorun/shared/lib-gui-panel-shared.lua:6: attempt to call field 'FindInLua' (a nil value)
1. unknown - addons/wire-extras-master/lua/autorun/shared/lib-gui-panel-shared.lua:6
   1. include - [C]:-1
   2. unknown - addons/wire-extras-master/lua/autorun/client/lib-gui-panel-client.lua:1

[ERROR] addons/wire-extras-master/lua/autorun/client/lib-gui-panel-client.lua:154: bad argument #2 to 'CreateFont' (table expected, got number)
1. CreateFont - [C]:-1
   1. unknown - addons/wire-extras-master/lua/autorun/client/lib-gui-panel-client.lua:154

(@addons/wire-extras-master/lua/entities/gmod_wire_hud_indicator_2/cl_init.lua (line 1))

[ERROR] addons/wire-extras-master/lua/entities/gmod_wire_hud_indicator_2/cl_init.lua:1: Module not found!
1. require - [C]:-1
   1. unknown - addons/wire-extras-master/lua/entities/gmod_wire_hud_indicator_2/cl_init.lua:1

**Comment by UAVXP** [comment]
#40 - waiting to approve my pull request to fix this error

**Comment by thegrb93** [comment]
I'm assuming those fixed the error
