### ISSUE TITLE
<text> Always Errors

### ISSUE THREAD

**Issue by Gorzoid** [wiremod/wire-extras#47]
The two lines in https://github.com/wiremod/wire-extras/blob/master/lua/entities/gmod_wire_hud_indicator_2/renderer/tags/primitives.lua#L436-L437 cause the code to always fail. From what I can see the value and font are always strings not tables, because EXPR_Parser:Calc pushes the value of the token rather than the token itself. This should be able to be fixed easily by removing these 2 lines.

**Comment by TomyLobo** [comment]
I fixed your link.

**Comment by Anticept** [comment]
Many things from wire extras were sitting in two branches that had basically been frozen for years. Some of it was prior to gmod 11 update.  Some of the items may not work well or at all.  If deleting those two lines makes things work, then I don't see why they can't be removed.
