### ISSUE TITLE
E2 effects extension could use some sort of manual, and maybe an overhaul?

### ISSUE THREAD

**Issue by HungarianPatriot** [wiremod/wire-extras#48]
E2 effects extension seem to have a great potential, however, the lack of a comprehensive manual for it makes it very hard to use. I managed to figure out the basics by myself, I can play certain effects at a desired position and set the angle of some, but that's about it. 

Most effects that I tried, even though they are probably valid, won't play at all. Most effect related functions seem to have no effect at all either, I suspect them to be broken, but maybe it's just the lack of information, and consequently my lack of knowlege that makes them appear to be like that. Examples are (sorry if the function names are not entirely correct, I write them off the top of my head) setAngle, setScale, setMagnitude, setDamageType, setFlags, setStart.

The effects extension could really use some explaination, and fixing where necessary.

**Comment by Divran** [comment]
The effects extension is in official wire (but disabled by default). You're in the wrong repo

**Comment by Divran** [comment]
Also, here's your manual http://wiki.garrysmod.com/page/Category:CEffectData
