### ISSUE TITLE
Attraction field generator crashes the server

### ISSUE THREAD

**Issue by Smartjer123** [wiremod/wire-extras#50]
When ever you turn it on the server crashes.

**Comment by oldmud0** [comment]
We need logs, crash dumps, etc.

**Comment by Smartjer123** [comment]
world (2) at -58.3 9.7 50.5 in contact with player_crouch (2) at -nan -nan -nan, crash. dist = -1, minq = 99999999999999997704951326524533662844684271992415000612999597473199345218078991130326129448151154688.000000
Could not find steamerrorreporter binary. Any minidumps will be uploaded in-processCould not find steamerrorreporter binary. Any minidumps will be uploaded in-processworld (2) at -58.3 9.7 50.5 in contact with player_crouch (2) at -nan -nan -nan, crash. dist = -1, minq = 99999999999999997704951326524533662844684271992415000612999597473199345218078991130326129448151154688.000000

world (2) at -58.3 9.7 50.5 in contact with player_crouch (2) at -nan -nan -nan, crash. dist = -1, minq = 99999999999999997704951326524533662844684271992415000612999597473199345218078991130326129448151154688.000000

**Comment by Smartjer123** [comment]
There you go.

**Comment by Smartjer123** [comment]
Has this been fixed yet because it still crashed on workshop version ?

**Comment by thegrb93** [comment]
I don't think this has the ability to crash the server, but if it does, a way to reproduce would be good.

**Comment by thegrb93** [comment]
There is divide by 0 https://github.com/wiremod/wire-extras/blob/master/lua/entities/gmod_wire_field_device/init.lua#L520

That should be limited to 1e-5 or something.
