### ISSUE TITLE
Modular Panel - Wire Tab Category

### ISSUE THREAD

**Issue by quantumdude836** [wiremod/wire-extras#54]
NOTE: this is a minor visual issue

The modular panel STool (`lua/weapons/gmod_tool/stools/wire_modular_panel.lua`) has category set to "Wire - I/O". However, the slash is interpreted as a separator for sub-categorization; thus, instead of the tool appearing in the "Wire - I/O" category, it appears in the "O" subcategory of "Wire - I".

**Comment by Divran** [comment]
Looks like this entity was created before I made the custom wire tab, but it wasn't added to the master branch of wire extras until way after. So it's still using the old style categories. I wonder if there's any other entities like this as well
