### ISSUE TITLE
E2 function holoSetPose cannot affect multiple pose parameters

### ISSUE THREAD

**Issue by MagnumMacKivler** [wiremod/wire-extras#55]
Hello,
So I noticed a while back that the holoAnim extension had E2 functions for pose parameters, and I decided to try and make a model that uses them. I got halfway through making it work when I discovered a very strange problem; it seems that the `holoSetPose()` function can only affect one pose parameter at a time.

A more technical way of describing the problem is that **when `holoSetPose()` is used to set a pose parameter, all other pose parameters appear to reset to their "zero" position.**

At first I thought it was a problem with just my model, so I did a test using the HL2 Jeep/buggy model, which uses pose parameters to move the wheels up and down (among other things).

This is the test E2 I made, as you can see it's pretty simple.
```
@name Pose Parameter Test
@inputs Left Right
@outputs 
@persist 
@trigger 

if(first()){
    holoCreate(0,entity():pos(),vec(1),entity():angles(),vec(255),"models/buggy.mdl")
}

holoSetPose(0,"vehicle_wheel_fl_height",Left)
holoSetPose(0,"vehicle_wheel_fr_height",Right)
```
Controlling the first pose parameter works fine. This is what happens when I lowered the first wheel:
![alt text](https://i.imgur.com/k9HJcfr.jpg "First Pose Parameter")

This is what happens when I try the other one independently:
![alt text](https://i.imgur.com/CbMow4O.jpg "Second Pose Parameter")

This is where the bug occurs. Setting the First, then the Second, does this:
![alt text](https://i.imgur.com/ckmUnfd.jpg "Both at once")

When the sequence is reversed, the same thing happens, but it affects the other wheel:
![alt text](https://i.imgur.com/pysad26.jpg "Reversed Sequence")

Examining the model in HLMV shows both wheels being controllable at the same time; This only makes sense as both source vehicles and certain addons such as Simfphys use all necessary pose parameters to make their vehicles work.
![alt text](https://i.imgur.com/cruzjLj.jpg "HLMV")

I have not tested `holoGetPose()` to see if it correctly retrieves the pose parameter info.

Thanks for your time and attention, and please let me know if you need any more information relating to the issue.

**Comment by bigdogmat** [comment]
Wiki page doesn't seem to indicate this should happen, though it does say we should call http://wiki.garrysmod.com/page/Entity/InvalidateBoneCache. I'll give that a try once I have a chance.

**Comment by MagnumMacKivler** [comment]
Thanks, I really appreciate it!

**Comment by bigdogmat** [comment]
Do you have your buttons set to toggle? I've just pasted this chip but replaced the `Left` and `Right` variables with constants (0 or 1), it's working as expected.

**Comment by Monkatraz** [comment]
You can tell their toggled because those buttons lights are both on at the same time.

**Comment by bigdogmat** [comment]
I see. After testing again it I can see the issues, though I don't know of a way to fix it, my only guess would be this has to be called client side and http://wiki.garrysmod.com/page/Entity/InvalidateBoneCache has to be called.

**Comment by mrmegacarlo** [comment]
Any progress on this?

**Comment by CalocoDoesGit** [comment]
Any progress on this?

**Comment by thegrb93** [comment]
I don't think InvalidateBoneCache is needed for serverside SetPoseParameter. I might try it tonight. I'm feeling in the fixing mood.

**Comment by MagnumMacKivler** [comment]
Awesome!

**Comment by thegrb93** [comment]
This code works
`lua_run local e=ents.FindByClass("gmod_wire_hologram")[1] hook.Add("Think","",function() local x=(math.sin(CurTime())+1)/2 for i=0, e:GetNumPoseParameters()-1 do e:SetPoseParameter(e:GetPoseParameterName(i), x) end end)`

**Comment by thegrb93** [comment]
This code also works
`lua_run local e=ents.FindByClass("gmod_wire_hologram")[1] local x=1 e:SetPoseParameter("vehicle_wheel_fl_height",x) e:SetPoseParameter("vehicle_wheel_fr_height",x)`

**Comment by thegrb93** [comment]
This code works too
`lua_run local e=ents.FindByClass("gmod_wire_hologram")[1] hook.Add("Think","",function() local x=(math.sin(CurTime())+1)/2 e:SetPoseParameter("vehicle_wheel_fl_height",x) e:SetPoseParameter("vehicle_wheel_fr_height",1-x) end)`

**Comment by thegrb93** [comment]
I see the problem. When you feed it a value that matches its previous value, it will reset to 0 when the other pose parameters are set.

**Comment by thegrb93** [comment]
```
@name Pose Parameter Test
@inputs Left Right
@outputs 
@persist 
@trigger 

if(first()){
    holoCreate(0,entity():pos(),vec(1),entity():angles(),vec(255),"models/buggy.mdl")
}

Hash = sin(curtime())/10

holoSetPose(0,"vehicle_wheel_fl_height",Left+Hash)
holoSetPose(0,"vehicle_wheel_fr_height",Right+Hash)
```

**Comment by thegrb93** [comment]
This works

**Comment by thegrb93** [comment]
The only solution is to network it client-side, and set them that way.

**Comment by MagnumMacKivler** [comment]
How easy/difficult would that end up being?

**Comment by thegrb93** [comment]
Pretty easy

**Comment by thegrb93** [comment]
serverside is done, now clientside.

**Comment by thegrb93** [comment]
Try out https://github.com/wiremod/wire-extras/pull/64 . Not tested fully but seems to work.
