### ISSUE TITLE
Wire modular panel tool out of date

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire-extras#63]
[ERROR] addons/wire-extras/lua/weapons/gmod_tool/stools/wire_modular_panel.lua:68: bad argument #2 to 'Exists' (string expected, got no value)
  1. Exists - [C]:-1
   2. LeftClick - addons/wire-extras/lua/weapons/gmod_tool/stools/wire_modular_panel.lua:68
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:228

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire-extras/blob/master/lua/weapons/gmod_tool/stools/wire_modular_panel.lua#L68

Needs a path argument. "DATA" http://wiki.garrysmod.com/page/file/Exists

**Comment by thegrb93** [comment]
Looks like all the 'file' functions in that tool need to be updated.

**Comment by TomyLobo** [comment]
doesn't look like it's the only thing that does in that file.
@deathking61 do you think you can find and fix all the places that need a ', "DATA"' and tell us if that makes it work?

**Comment by thegrb93** [comment]
@TomyLobo pretty sure he's not a coder.

**Comment by thegrb93** [comment]
This entity is completely broken. I fixed it a little bit, but someone else needs to do the rest.

**Comment by EdoTM** [comment]
Isn't this issue a duplicate of #97?

**Comment by thegrb93** [comment]
That one is a duplicate of this. We can supersede this one with that one.
