### ISSUE TITLE
Remove gui Panel Test adv

### ISSUE THREAD

**Issue by adamnejm** [wiremod/wire-extras#83]
Seriously, some test/debug entity in production?
Remove it, please.
`gmod_test_panel_adv`

**Comment by Divran** [comment]
is it spawnable ingame?

@Anticept according to git history this is your fault lel

**Comment by adamnejm** [comment]
Yep, spawnable by all and has no specified category so in most cases it's creating new category called Others in Entities menu ;f

**Comment by Anticept** [comment]
It's an extremely ancient entity that, if I recall, was basically a configurable GUI panel so that you could have sliders and such in it. Really neat before gmod 11(?) broke it.

We can purge it if needed.

**Comment by Anticept** [comment]
This should now be resolved. Let me know if it's still an issue.
