### ISSUE TITLE
Someone put a backdoor in your add-on and is hosting it on workshop

### ISSUE THREAD

**Issue by xSetrox** [wiremod/wire-extras#87]
https://steamcommunity.com/sharedfiles/filedetails/?id=799449579
He has a backdoor which allows him to selectively ban people from the server by sending a disconnect con command to the clients.
This exists in his add-on, in servermessage.lua, particularly on line 13. The table for banned users is modified using a tool he has that updates the workshop repo.
Sorry for posting this as an "issue", just thought you should know, and should maybe alert users of this as well.
Thanks.

**Comment by thegrb93** [comment]
I think the correct place to report this is robotboy655@facepunchstudios.com
